### ISSUE TITLE
Create tag / branches for early vector tile version. 

### ISSUE THREAD

**Issue by vincentsarago** [mapbox/vector-tile-base#13]
👋 @flippmoke, first thanks for your work on this great module. 

I'm using it to run simple tests on some vector tiles, but still in version 2. Latest commits seem to broke my tests (change from `properties` to `attributes`) I'm assuming this is a change to support vt3 ? 

To prevent other breaks would it be possible to create some tags/release or some stale branches (e.g `vt2`) ? 

Thanks

**Comment by flippmoke** [comment]
No, it was simply a change to have a more correct set of terminology. The newest version should support vt2 completely, if it does not please file a bug here.

**Comment by vincentsarago** [comment]
thanks @flippmoke, I guess I misunderstood the update ;-)
