### ISSUE TITLE
bug in _add_legacy_attributes causing duplicate values

### ISSUE THREAD

**Issue by asafco86** [mapbox/vector-tile-base#14]
@flippmoke 
in vector_tile_base/engine.py, function: _add_legacy_attributes you check to see if the value was already inserted to self_values by:
`if not (v in self._values and type(self._values[self._values.index(v)]) == type(v)):`

Scenario:
when self._values contains same value with different variable type then self._values.index(v) will always find the first one so all duplicates of the second value will be considered as unseen values and will be added as duplicates to the protobuf message.
e.g. [0, 0.0, 0.0, 0.0, 0.0, ....]

proposed solution: check all matching values in self._values:
e.g.
`

    def _is_in_values(self, val):

        found = False

        start_index = -1

        try:

            while not found:

                start_index = self._values.index(val, start_index + 1)

                if type(self._values[start_index]) == type(val):

                    found = True

        except ValueError:

            pass

        return found

`

**Comment by flippmoke** [comment]
@asafco86 could you please provide an example failing test case so that we can confirm this change works when I write a PR

**Comment by flippmoke** [comment]
Solved and wrote my own test case, please check if code in master works for you!
